# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    env:
      XCODE_VERSION: 'Xcode_16.3'
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode
      run: sudo xcode-select -s "/Applications/$XCODE_VERSION.app"
    - name: Test
      run: swift test --enable-code-coverage
    - id: coverage
      uses: codefiesta/swift-test-coverage-summary@65797b611badad8dcc8a1840e29ae9c1688e8dc3
    - name: badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{secrets.GIST_SECRET}}
        gistID: aff52838ae4b2f0175c4c703700bc133
        filename: coverage.json
        label: Coverage
        message: ${{steps.coverage.outputs.percentage}}%
        color: white
