# This workflow generates Swift DocC documentation and publishes to Github pages
# https://github.com/marketplace/actions/swift-doc
name: Documentation

on: [push]

jobs:

  build:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - uses: sersoft-gmbh/swifty-docs-action@v3
