# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    env:
      XCODE_VERSION: 'Xcode_16.4'
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode
      run: sudo xcode-select -s "/Applications/$XCODE_VERSION.app"
    - name: Install SwiftLint
      run: brew install swiftlint
    - name: Lint
      run: swiftlint lint --strict --quiet
    - name: Build
      run: swift build -v
    - name: Test
      run: swift test --enable-code-coverage
    - name: Generate Docs
      uses: SwiftDocOrg/swift-doc@master
      with:
        inputs: Sources
        module-name: OAuthKit
        output: docs
    - name: Upload Docs
      uses: SwiftDocOrg/github-wiki-publish-action@v1
      with:
        path: docs
      env:
        GH_PERSONAL_ACCESS_TOKEN: ${{secrets.GIST_SECRET}}
    - id: coverage
      uses: codefiesta/swift-coverage-action@0.0.4
    - name: badge
      # Only run the badge update if we are pushing to main
      if: github.ref == 'refs/heads/main'
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{secrets.GIST_SECRET}}
        gistID: 87655b6e3c89b9198287b2fefbfa641f
        filename: oauthkit-coverage.json
        label: Coverage
        message: ${{steps.coverage.outputs.percentage}}%
        color: white
